"""empty message

Revision ID: afbddb916d98
Revises: 4b5cae460ca3
Create Date: 2025-02-19 18:29:44.419387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbddb916d98'
down_revision = '4b5cae460ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keylogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keylogs', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
